version: '3'

services:

  frontend:
    build: 'frontend'
    environment:
      CI: 'true'
      DANGEROUSLY_DISABLE_HOST_CHECK: 'true'
    volumes:
      - './frontend/src:/srv/src'
    ports:
      - '5173:5173'

  backend:
    build: 'backend'
    environment:
      DEBUG: 'app'
      GOOGLE_SPREADSHEET_ID: ${GOOGLE_SPREADSHEET_ID}
      GOOGLE_SHEETS_API_KEY: ${GOOGLE_SHEETS_API_KEY}
      OPEN_LEGISLATION_KEY: ${OPEN_LEGISLATION_KEY}
      OPEN_STATES_KEY: ${OPEN_STATES_KEY}
      # DEBUG: express:*
    volumes:
      - './backend/src:/srv/src'
    ports:
      - '3001:3001'
